

raise Exception('Intentionally fail autodiscovery')